spring.application.name=client-oauth2

# Configuration du serveur
server.port=8080

# Configuration OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=ICI_ID_CLIENT
spring.security.oauth2.client.registration.google.client-secret=ICI_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Configuration du fournisseur (Provider)
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com

